server:
  port: 8082
#######MariaDb Database##############
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/paginationtest
    username: 
    password: 
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
###############################################################
