server:
  port: 8082
#######MariaDb Database##############
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/paginationtest
    username: root
    password: root2022
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
###############################################################

#######Postgres########################
#spring:
  #datasource:
    #url: jdbc:postgresql://localhost:5432/DemoTest
    #username: postgres
    #password: root
    #driver-class-name: org.postgresql.Driver
    #jpa:
    #show-sql: true
      #hibernate:
    #ddl-auto: update
      #properties:
      #hibernate:
    #format_sql: true
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
#############################################